#!/usr/bin/python

# Script for transcoding video files to several web acceptable
# formats/bitrates/resolutions

from __future__ import division
from ffprobe import FFProbe as ffprobe
import subprocess as subproc
import sys, os

def main():
    encoder = Encoder()

    encoder()

class Encoder(object):
    def __init__(self):
        self._error = Error()

        self._set_bit = True
        self._set_res = True

        self._options = [
            #[bitrate, x_res, y_res]
            [2000, 1920, 1080],
            [1200, 1280, 720 ],
            [700,  853, 480  ]
        ]
        self._formats = ['mp4', 'webm', 'ogg']

        self._get_video()
        self._init_defaults()

    def __call__(self, ext):
        print 'attempting to transcode your file...'

        to_run = []
        
        for cmds in self._options:
            to_run.append(self._get_command(cmds))

        for i in to_run:
            for x in i: subproc.check_output(x)
        
    def _get_command(self, encode):
        cmds = []
        for ext in self._formats:
            cmd    = []
            
            if ext in ('mp4', 'webm'):
                cmd.extend(['ffmpeg', '-i', self._source, '-c:a'])
            
                if ext == 'mp4':
                    cmd.extend(['aac', '-strict', '-2', '-c:v', 'libx264',
                                '-f', 'mp4', '%s.mp4'%(encode[2]), '-crf', '23'
                    ])
                else:
                    cmd.extend(['libvorbis', '-c:v', 'libvpx', '-f', 'webm', '%s.webm'%(encode[2])])

                cmd.extend(['-b:v', '%sk'%(encode[0]), '-b:a', '128k',
                            '-s', '%sx%s'%(encode[1], encode[2]), '-hide_banner'
                ])
                
            elif ext in ('ogg'):
                cmd.extend([
                    'ffmpeg2theora', self._source, '-o', '%s.ogv'%(encode[2]),
                    '--max_size', '%sx%s'%(encode[1], encode[2]),
                    '-V', '%sk'%(encode[0]), '-A', '128k'
                ])
            
            else: # This should never be triggered, all internal use
                self._error(6)

            cmds.append(cmd)
            
        return cmds
            
    def _init_defaults(self):
        # changes resolutions and bit rates according to what encoding
        # the video already has
        self._data = ffprobe(self._source)
        self._isVideo    = False
        self._resolution = (0,0)
        self._bitrate    = 0

        for stream in self._data.streams:
            if stream.isVideo():
                self._isVideo    = True
                self._resolution = stream.frameSize()
                self._bitrate    = stream.bitrate()

                break #break on first video stream

        if not self._isVideo:
            self._error(4, self._source)

        if self._bitrate == 0:
            err = ','.join([str(x[0])+'k/s' for x in self._options])
              # converts list of bitrates from `self._options` to strings:
              # [[2000, 1920, 1080],[1200, 1280, 720]] -> '2000ks,1200k/s'
            self._error(3, ['bitrate',  err])
            self._set_bit = False

        if self._resolution == (0,0):
            err = ','.join(['x'.join([str(x[1]), str(x[2])]) for x in self._options])
              # converts list of x/y's from `self._options` to strings:
              # [[2000, 1920, 1080],[1200, 1280, 720]] -> '1920x1080,1280x720'
            self._error(3, ['resolution', err])
            self._set_res = False
        else:
            self._aspect_ratio = self._resolution[0]/self._resolution[1]

        if self._set_bit or self._set_res:
            for encoding in self._options:

                if self._set_bit:
                    if self._bitrate < encoding[0]*1000:
                        encoding[0] = self._bitrate//1000

                if self._set_res:
                    encoding[1] = int(encoding[2] * self._aspect_ratio)
                    if encoding[1]%2 != 0: encoding[1] += 1 # make sure x/y
                    if encoding[2]%2 != 0: encoding[2] += 1 # vals are even


    def _get_video(self):
        # validation should be more strict here, spaces in file names
        # have the potential to mess everything up
        if len(sys.argv) < 2:
            self._error(0)

        self._source = sys.argv[1]

        # ffprobe cannot read filenames with spaces
        if ' ' in self._source:
            self._error(5, self._source)

        if not os.path.isfile(self._source):
            self._error(1, self._source)


class Error(object):
    def __init__(self):
        self._errors = [
            ("Missing filename argument", True),#------------------------------------#0
            ("Could not locate file '{}'", True),#-----------------------------------#1
            ("Could not transcode to '.{}'", False),#--------------------------------#2
            ("Could not determine {} of video - exectuing with defaults: {}", False),#3
            ("Missing video stream, is '{}' not a video?", True),#-------------------#4
            ("'{}' is an invalid name, use only names without whitespace", True),#---#5
            ("Internal error, exiting...", True)#------------------------------------#6
        ]

    #insert must be a list or tuple to avoid weird error printing
    def __call__(self, id, insert=None):
        if insert and (type(insert) is not list and type(insert) is not tuple):
            insert = [insert]

        msg = self._errors[id][0]; msg = msg.format(*insert) if insert else msg

        print '\nERROR: %s\n' % msg

        if self._errors[id][1]:
            sys.exit()


if __name__ == "__main__":
    main()



# ffmpeg -i {0} -c:a aac -strict -2 -b:a 128k -c:v libx264 -f mp4 -b:v {1}k -s {2} {3}.mp4 -crf 23 -hide_banner
# ffmpeg -i {0} -c:v libvpx -b:v {1}k -c:a libvorbis -b:a 128k -s {2} -f webm {3}.webm -hide_banner
# ffmpeg2theora {0} -o {3}.ogv --max_size {2} -V {1}k -A 128k
