#!/usr/bin/python

# Script for transcoding video files to several web acceptable
# formats/bitrates/resolutions

# NOTES:
# + To determine what to transcode to, use a sort of "checkbox"
# - whereby anything that is False when checked should be transcoded
# - to, anything that is True should be considered done/not needed

from __future__ import division
from ffprobe import FFProbe as ffprobe
import subprocess as subproc
import sys, os

# Change this for security purposes
CALLS = [
    "ffmpeg -i {0} -c:a aac -strict -2 -b:a 128k -c:v libx264 -f mp4 -b:v {1}k -s {2} {3}.mp4 -crf 23 -hide_banner",
    "ffmpeg -i {0} -c:v libvpx -b:v {1}k -c:a libvorbis -b:a 128k -s {2} -f webm {3}.webm -hide_banner",
    "ffmpeg2theora {0} -o {3}.ogv --max_size {2} -V {1}k -A 128k"
]
ERRORS = [
    ("Missing filename argument", True),
    ("Could not locate file '{}'", True),
    ("Could not transcode to '.{}'", False)
]
OPTS = [
    [2000, 1920, 1080],
    [1200, 1280, 720 ],
    [700,  853, 480  ]
]


def main():
    #get/validate vid name
    source = get_video()

    init_opts(source)

    transcode(source)

def transcode(source):
    for encode in OPTS:
        params = [source, encode[0], '%sx%s'%(encode[1],encode[2]), 'new.%s'%(encode[2]) ]
        print params
        call_ffmpeg(0, params)
        call_ffmpeg(1, params)
        call_ffmpeg(2, params)
        
    
def init_opts(source):
    # changes resolutions and bit rates according to what format the video is already in
    data = ffprobe(source)

    for stream in data.streams:
        if stream.isVideo():
            reso = stream.frameSize()
            bitrate = stream.bitrate()
            a_ratio = reso[0]/reso[1]

            break

    
    for encoder in OPTS:
        if bitrate != 0:
            if bitrate < encoder[0]*1000:
                encoder[0] = bitrate//1000

        if a_ratio != 0:
            encoder[1] = int(encoder[2] * a_ratio)
            if encoder[1]%2 != 0: encoder[1] += 1
        
def get_video():
    # validates command line args
    if len(sys.argv) < 2:
        error(0)

    video_name = sys.argv[1]

    if not os.path.isfile(video_name): error(1, video_name)

    return video_name


def call_ffmpeg(id, opts):
    cmd = CALLS[id].format(*opts)

    try:
        subproc.call(cmd ,shell=True)
    except:
        error(2, ext)

def error(id, insert=None):
    #insert must be a list or tuple to avoid weird error printing
    if insert:
        if insert is not list or insert is not tuple:
            insert = [insert]

    msg = ERRORS[id][0]; msg = msg.format(*insert) if insert else msg

    print '\nERROR: %s\n' % msg

    if ERRORS[id][1]:
        sys.exit()


if __name__ == "__main__":
    main()
