#!/usr/bin/python
from __future__ import division
from ffprobe import FFProbe as ffprobe
import subprocess as subproc
import sys, os, signal, tempfile

def main(encoder):
    try:
        encoder()
    except(KeyboardInterrupt, SystemExit):
            print 'cleaning'
            #encoder.clean()
            print 'exiting'
    else:
        print 'Encoding Complete'
        print 'Exiting'

    sys.exit()

class Encoder(object):
    def __init__(self):
        print 'Starting encoder'
        self.temp_files = []
        self.error = Error()

        self._set_bit = True
        self._set_res = True

        #bitrate, x, y
        self.options = [
            [2000, 1920, 1080],
            [1200, 1280, 720 ],
            [700,  853, 480  ]
        ]
        self.formats = ['mp4', 'webm', 'ogg']

        self._get_video()
        self._init_defaults()
        self._arg_builder()

    def __call__(self):


    def _arg_builder(self):
        self.cmds = []

        for opts in self.options:
            for idx, ext in enumerate(self.formats):

                self.args  = ['ffmpeg', '-loglevel', '24',
                              '-i', self.source, '-c:v']

                # video codec
                if idx == 0  : self.args.extend(['libx264'])
                elif idx == 1: self.args.extend(['libvpx'])
                elif idx == 2: self.args.extend(['libtheora'])
                else         : self.error(6)

                self.args.extend(['-c:a'])

                #audio codec
                if idx == 0:
                    self.args.extend(['aac', '-strict', '-2'])
                else: self.args.extend(['libvorbis'])

                self.args.extend([
                    '-b:v', '%sk'%(opts[0]),
                    '-b:a', '128k', '-s',
                    '%sx%s'%(opts[1],opts[2]), ext
                ])

                if idx == 0: self.args.extend(['-crf', '23'])

                self.args.extend(['-y','-hide_banner'])

                self.cmds.append(self.args)

        for x in self.cmds:
            print ' '.join(x)

    def _get_video(self):
        # validation should be more strict here, spaces in file names
        # have the potential to mess everything up
        if len(sys.argv) < 2:
            self.error(0)

        self.source = sys.argv[1]

        # ffprobe cannot read filenames with spaces
        if ' ' in self.source:
            self.error(5, self.source)
        elif not os.path.isfile(self.source):
            self.error(1, self.source)

    def _init_defaults(self):
        # changes resolutions and bit rates according to what encoding
        # the video already has
        self._data = ffprobe(self.source)
        self._cur        = []
        self._isVideo    = False
        self._resolution = (0,0)
        self._bitrate    = 0

        for stream in self._data.streams:
            if stream.isVideo():
                self._isVideo    = True
                self._resolution = stream.frameSize()
                self._bitrate    = stream.bitrate()

                break #break on first video stream

        if not self._isVideo:
            self.error(4, self.source)

        if self._bitrate == 0:
            err = ','.join([str(x[0])+'k/s' for x in self.options])
              # converts list of bitrates from `self.options` to strings:
              # [[2000, 1920, 1080],[1200, 1280, 720]] -> '2000ks,1200k/s'
            self.error(3, ['bitrate',  err])
            self._set_bit = False

        if self._resolution == (0,0):
            err = ','.join(['x'.join([str(x[1]), str(x[2])]) for x in self.options])
              # converts list of x/y's from `self.options` to strings:
              # [[2000, 1920, 1080],[1200, 1280, 720]] -> '1920x1080,1280x720'
            self.error(3, ['resolution', err])
            self._set_res = False
        else:
            self._aspect_ratio = self._resolution[0]/self._resolution[1]

        if self._set_bit or self._set_res:
            for encoding in self.options:

                if self._set_bit:
                    if self._bitrate < encoding[0]*1000:
                        encoding[0] = self._bitrate//1000

                if self._set_res:
                    encoding[1] = int(encoding[2] * self._aspect_ratio)
                    if encoding[1]%2 != 0: encoding[1] += 1 # make sure x/y
                    if encoding[2]%2 != 0: encoding[2] += 1 # vals are even


class Error(object):
    def __init__(self):
        self._errors = [
            ("Missing filename argument", True),#------------------------------------#0
            ("Could not locate file '{}'", True),#-----------------------------------#1
            ("Could not transcode to {}", False),#-----------------------------------#2
            ("Could not determine {} of video - exectuing with defaults: {}", False),#3
            ("Missing video stream, is '{}' not a video?", True),#-------------------#4
            ("'{}' is an invalid name, use only names without whitespace", True),#---#5
            ("Internal error, exiting...", True)#------------------------------------#6
        ]

    #insert must be a list or tuple to avoid weird error printing
    def __call__(self, id, insert=None):
        if insert and (type(insert) is not list and type(insert) is not tuple):
            insert = [insert]

        msg = self._errors[id][0]; msg = msg.format(*insert) if insert else msg

        print '\nERROR: %s\n' % msg

        if self._errors[id][1]:
            sys.exit()


def outfile_open(**kwargs):
    if 'mode' not in kwargs: kwargs['mode'] = 'wb'
    if 'dir'  not in kwargs: kwargs['dir']  = '.'
    kwargs['delete'] = False
    return tempfile.NamedTemporaryFile(**kwargs)

def outfile_commit(temp_file, target_name, chmod=0644):
    if chmod: os.chmod(temp_file.name, chmod)
    os.rename(temp_file.name, target_name)

def outfile_cancel(temp_file):
    os.unlink(temp_file.name)

if __name__ == "__main__":
    main(Encoder())
